### ISSUE TITLE
Blog Post - About Author

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/LyntonWeb#17]
https://usersnap.com/a/#/your-team-wods/p/sims-f0ed74fc/88
Could not test this issue, need a blog post that contains the info with picture and description as seen in the issue created by the client.
Please advise.

**URL tested:** http://blog.simsbuilders.com/blog/home-completion

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=5.0&device=Motorola+Moto+G+2nd+Gen&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fblog.simsbuilders.com%2Fblog%2Fhome-completion&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://blog.simsbuilders.com/blog/home-completion) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Motorola Moto G 2nd Gen |
| Browser | Mobile_chrome |
| Operating System | Android 5.0 |
| Resolution | 720 x 1280 px |
| Screen size | 5.0 in - 2.4 x 4.3 in |
| Viewport | 360 x 640 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/30c279e5aec1a4a4da8a3b50b0d9e05fb64bf89c/realdroid_Motorola_Moto_G_2nd_Gen.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/30c279e5aec1a4a4da8a3b50b0d9e05fb64bf89c/realdroid_Motorola_Moto_G_2nd_Gen.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=android&os_version=5.0&device=Motorola+Moto+G+2nd+Gen&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fblog.simsbuilders.com%2Fblog%2Fhome-completion&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://blog.simsbuilders.com/blog/home-completion) to reproduce the issue on Browserstack:**

**Comment by computan** [comment]
There is no information for that specific author.
