### ISSUE TITLE
Monthly Updates box

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/LyntonWeb#18]
This issue is marked as resolved but it still needs work:
https://usersnap.com/a/#/your-team-wods/p/sims-f0ed74fc/86
The Email field and the Subscribe button are not the same size.
Also, they are not centered. Depending on the screen size they move to one side or the other (tested in 1024px and 1280)

The size (height and width) of the input field and button should also be revised. See below comment.

**URL tested:** http://blog.simsbuilders.com/blog

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Firefox&browser_version=63.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=1280x1024&url=http%3A%2F%2Fblog.simsbuilders.com%2Fblog&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://blog.simsbuilders.com/blog) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Firefox 63.0 |
| Operating System | Windows 10 |
| Resolution | 1280x1024 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/2d1dce76338663b811ef7680ba633fd677fa4850/win10_firefox_63.0.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/2d1dce76338663b811ef7680ba633fd677fa4850/win10_firefox_63.0.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Firefox&browser_version=63.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=1280x1024&url=http%3A%2F%2Fblog.simsbuilders.com%2Fblog&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://blog.simsbuilders.com/blog) to reproduce the issue on Browserstack:**

**Comment by NM-Computan** [comment]
https://xd.adobe.com/spec/4ad85654-5aff-45a9-41f7-be6e4153b951-3ce9/screen/9f206b55-c661-43ed-a580-26a7494d6d80/sims-blog-2col-mockup-1920/

![image](https://user-images.githubusercontent.com/45298471/49112825-8ff21280-f272-11e8-825a-5ccab1cfe3b4.png)

**Comment by computan** [comment]
Done
