### ISSUE TITLE
Logo margins

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/LyntonWeb#3]
Check margins on logo. They should be 25px top, left, and bottom.

**URL tested:** https://blog.simsbuilders.com/test

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fblog.simsbuilders.com%2Ftest&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://blog.simsbuilders.com/test) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1920x938 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/2034075c3fff6e3f357259450311dec8a2eaf431/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/2034075c3fff6e3f357259450311dec8a2eaf431/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fblog.simsbuilders.com%2Ftest&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://blog.simsbuilders.com/test) to reproduce the issue on Browserstack:**

**Comment by NM-Computan** [comment]
![image](https://user-images.githubusercontent.com/45298471/48959763-55246d80-ef46-11e8-896b-f5aad502c773.png)

**Comment by computan** [comment]
Done
