### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/LyntonWeb#4]
The buttons are not centered vertically. 
Also, the underline should be resting on the edge of the menu background (see comment below).

**URL tested:** https://blog.simsbuilders.com/test

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fblog.simsbuilders.com%2Ftest&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://blog.simsbuilders.com/test) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1920x938 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/e2a6daae5d74606472f50dab041d43370a861c88/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/e2a6daae5d74606472f50dab041d43370a861c88/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fblog.simsbuilders.com%2Ftest&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://blog.simsbuilders.com/test) to reproduce the issue on Browserstack:**

**Comment by NM-Computan** [comment]
![image](https://user-images.githubusercontent.com/45298471/48959840-00cdbd80-ef47-11e8-9980-e261e2cfa60f.png)

**Comment by computan** [comment]
Done
