### ISSUE TITLE
Dropdown buttons

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/LyntonWeb#7]
Colour for active dropdown should be #2E97BF

**URL tested:** https://blog.simsbuilders.com/test#

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fblog.simsbuilders.com%2Ftest%23&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://blog.simsbuilders.com/test#) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1920x938 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/32ed23420d42748b07a8fc21745b3354f0e2ff6c/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/32ed23420d42748b07a8fc21745b3354f0e2ff6c/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fblog.simsbuilders.com%2Ftest%23&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://blog.simsbuilders.com/test#) to reproduce the issue on Browserstack:**

**Comment by computan** [comment]
Done

**Comment by rashedaleecom** [comment]
![image](https://user-images.githubusercontent.com/25958001/49033019-5a83f100-f1ae-11e8-9a21-d187abe78479.png)

In this moment we have only dropdown arrow on hover

**Comment by computan** [comment]
Done
